In [15]:
x=[100,-200,300,-400]
y=[1,0,1,0]


In [16]:
X_array=np.array(x).reshape(-1,1)
print(X_array)
print("\n")
Y_array=np.array(y).reshape(-1,1)
print(Y_array)

[[ 100]
 [-200]
 [ 300]
 [-400]]


[[1]
 [0]
 [1]
 [0]]


In [10]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

In [18]:
model= DecisionTreeClassifier()


In [19]:
model.fit(X_array,Y_array)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [26]:
model.predict([[-2]])
# test_data=[100]
# test_data_array=np.array(test_data).reshape(-1,1)
# print(test_data_array)

array([1])

In [1]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test, pred_logreg)
print("Confusion matrix:\n{}".format(confusion))

NameError: name 'y_test' is not defined

In [1]:
import tensorflow as tf

D:\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
print(tf.__version__)

2.0.0
