In [1]:
#Label Encoder and one hot encoder

import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
data = ['cold','warm','hot','middle']
values = np.array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
label_encoder_model = label_encoder.fit(values)
print(label_encoder_model.classes_)
label_encoder_temp = label_encoder_model.transform(values)
print(label_encoder_temp)

onehot_encoder = OneHotEncoder(sparse=False)
label_encoder_temp_reshaped = label_encoder_temp.reshape(len(label_encoder_temp), 1)
print(label_encoder_temp_reshaped)
onehot_encoder = onehot_encoder.fit(label_encoder_temp_reshaped)
one_hot_encoded_temp = onehot_encoder.transform(label_encoder_temp_reshaped)
print(one_hot_encoded_temp)

['cold' 'warm' 'hot' 'middle']
['cold' 'hot' 'middle' 'warm']
[0 3 1 2]
[[0]
 [3]
 [1]
 [2]]
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
